# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 08:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_auto_20170402_1847'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['add_date']},
        ),
        migrations.AddField(
            model_name='image',
            name='add_date',
            field=models.DateField(default=datetime.datetime(2017, 4, 7, 8, 11, 38, 720825, tzinfo=utc)),
        ),
    ]
