# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 08:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_auto_20170407_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='add_date',
            field=models.DateField(default=datetime.datetime(2017, 4, 7, 8, 12, 30, 472308, tzinfo=utc)),
        ),
    ]
